jobs:
  release:
    uses: githubcdr/workflows/.github/workflows/docker-release.yml@main
    with:
      image_name: learn-golang
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}
